### ISSUE TITLE
complete overhaul and revert to C backend

### ISSUE THREAD

**Issue by rmarquis** [rmarquis/pacaur#708]
Looking back, the history of dependency resolution in pacaur is a true roller-coster, going from relying exclusively on the solver and PKGBUILD parser provided by cower to being entirely internally handled through the more modern AUR RPCv5 in pacaur code.

I've however recently learned that a [better cower](https://github.com/falconindy/cower/issues/136) is in the pipeline - no ETA yet though. It will move to multiinfo, and should be able to handle the edge cases better (split packages, versioning issues). These were the reasons that made me move the solver to the bash side gradually, and what should have been a temporary solution simply became permanent (see #50, #149, #153, #235, and probably quite a few others).

Now, there is the opportunity to go back to the original vision as a simple glue code between tiny C utilities. Most of the complexity of the internal, duplicate code could be dropped, the maintenance burden of that code could be shared, and pacaur could focus exclusively on the "fast workflow" concept and the more useful tasks done by more 'complete' helpers.

Using the new cower as full backend, here are some medium and long term plans:
- [ ] drop all json code (drop #702)
- [ ] drop internal AUR dependency solver (drop #652)
- [ ] replace weak `pacman -Sp` calls by expac (probably requires some patchs, #267)
- [ ] optimize repo deps solver (replace pactree by expac?, #575)
- [ ] investigate the use of a local repo (#643)
- [ ] drop complex split packages code if local repo is used
- [ ] use pacutils in [community] where adequate (#433)
- [ ] make all functions modular 
- [ ] reuse makepkg routines where possible
- [ ] reorganise the code (see pacaur50 branch, #443)
- [ ] improve internal readability (#443)

The one point I am not sure being worthwhile is using a local repo. While it will simplifly the split package code, that code is working relatively well, and I am not sure about the work involved and pitfall, specially regarding the fast workflow concept (though AladW cleared the way with aurutils here).

Some of the other ideas could be introduced gradually, or separately in the pacaur50 branch. Priority should be given to patching upstream tools (expac/pactree) if relevant.

**Comment by AladW** [comment]
A small note on `pactrans`, probably the most interesting use is that it can install and remove packages in one transaction:
`pacinstall foo --remove bar`
which might remove the need to use pacman's `--ask` option.

**Comment by rmarquis** [comment]
Sounds great indeed. There is a note in pacutils README, although I'm not sure what it specifically refers to:
> pactrans, pacinstall, pacremove
> Install/remove packages in a single transaction
>
>NOTE: alpm support for installation and removal in a single transaction is flaky; some options may be ignored.

**Comment by rmarquis** [comment]
Some update about the expected timeline:

I am giving up on the idea of using a local repo (#643). Too many painful quirks, workarounds needed and uncertainty for a "nicer" design that mostly doesn't solve any issue relevant to the scenario pacaur is originally designed for. For anyone interested, it would probably make more sense to built a new interface upon aurutils instead.

Also, while I expected the `4.8.x` branch to be released with auracle support instead of cower, the former still needs to mature before the switch is possible. There are some bugfixes and improvements waiting to be released, so I'll just release that new branch with cower as a dependency.

Here's the new timeline:
**4.8.x**: usual small addition and bugfixes maintenance.
**4.9.x**: moving to auracle info/search, and ditching cower.
**5.x**: rework to make the code cleaner and more modular. Full compatibility with pacman/makepkg 5.1, usage of pacutils and auracle solver.

While auracle isn't ready yet, I'd like to start working on `5.x` by first getting the internal solver and RPC calls in a temporary separate module, mimicking the expected behavior of auracle. Once auracle is fully ready, the switch to its solver could be very easily done.

**Comment by ChuckDaniels87** [comment]
Recently, I've been working on continuous integration and code tests. I think that adding tests and CI to `pacaur` could be really interesting to detect regressions and bugs. In fact, this is even more important for the upcoming reworks in 5.x. What do you think about this? We could easily use Travis CI here.

**Comment by rmarquis** [comment]
Definitely yes! A test suite is the one thing I regret not having written from day one, as I spent so much time checking weird regression. I am not very familiar with testing framework, but I know that [Aurget](https://github.com/pbrisbin/aurget/) uses [cram](https://bitheap.org/cram/) which might be a candidate.
I've however no experience with CI apart from using travis with C projects, which only detects when a compilation fails.

**Comment by ChuckDaniels87** [comment]
> Definitely yes! A test suite is the one thing I regret not having written from day one, as I spent so much time checking weird regression. I am not very familiar with testing framework, but I know that Aurget uses cram which might be a candidate.

We can write our own tests in bash without using external frameworks, but `cram` looks nice in any case.

> I've however no experience with CI apart from using travis with C projects, which only detects when a compilation fails.

Well, it is quite easy to create tests even for C, C++ or other compiled languages. In the `pacaur` case, I was thinking two different types of tests for CI:
* Test functions independently. These tests could be implemented during the code rework. The idea is to check that every function is really doing what it is meant to.
* Test `pacaur` in an isolated/clean environment. Test `pacaur`installation and also run some `pacaur` operations in an ArchLinux Docker image. For example: download, build and install packages; search packages; specific operations tests (--ignore, etc.).

I've been working with GitLab CI in my team for building RPMs packages and C++ apps in CentOs 7. It works really well in combination with Docker. However, I am not sure how Travis CI would do with custom ArchLinux Docker images since it works by default in an Ubuntu environment. It seems that [it is possible](https://docs.travis-ci.com/user/docker/#Using-a-Docker-Image-from-a-Repository-in-a-Build), but we could look for some free alternatives if that is not good enough.

**Comment by ArchangeGabriel** [comment]
[fwupd does CI with Travis using the ArchLinux Docker image](https://github.com/hughsie/fwupd/blob/eba19fb94d883a0f74e65c39ffddd6bd9422ce5e/contrib/ci/Dockerfile-arch) The lines building the Docker and running things inside is [here](https://github.com/hughsie/fwupd/blob/eba19fb94d883a0f74e65c39ffddd6bd9422ce5e/.travis.yml).

**Comment by rmarquis** [comment]
There is very little code that wouldn't need to be rewritten to make full use of pacutils/makepkg utils functions or simply better practices (f.e., functions that return correct errors code). An overhaul would be better done from scratch, maybe even in a separate repo.

This could be also be the opportunity to practice Test Driven Development: write the tests first, then the code. [bats](https://github.com/sstephenson/bats) seems to be the ideal candidate.

**Comment by AladW** [comment]
IMO a more effective approach would be to address upstream issues in the AUR as to trivialize issues with writing clients. And when stuff like test frameworks is mentioned, filing fixes upstream would probably be less effort...

**Comment by rmarquis** [comment]
Generally agree with that, though I'm not sure which exact issues you're thinking about here.

Today, I've had a look at [FS#54906](https://bugs.archlinux.org/task/54906), but implementing it in a clean way doesn't seem trivial - even though there are rpmvercmp PHP implementation available. You either need to make individual SQL request to filter out versioned packages that do not have results before the main multiinfo SQL request, or store args versions somehow to filter the output of the main multiinfo SQL request. Might be more easily done client side with jq...

**Comment by ChuckDaniels87** [comment]
> There is very little code that wouldn't need to be rewritten to make full use of pacutils/makepkg utils functions or simply better practices (f.e., functions that return correct errors code). An overhaul would be better done from scratch, maybe even in a separate repo.

We could use `pacaur50` branch for this. In other case, should I stop maintaining it? Do you want to start completely from scratch?

**Comment by rmarquis** [comment]
> In other case, should I stop maintaining it? Do you want to start completely from scratch?

Yes. I did some minor work locally to "test the water", and it will be faster than changing some part then adjusting the relevant bits steps by steps in the rest of the code. The main files structure discussed in `pacaur50` is useful and can be kept as reference.

I don't think GH renames links of cross referenced issues. Using a new branch rather than a new repo might avoid a complete mess.

**Comment by ChuckDaniels87** [comment]
> I don't think GH renames links of cross referenced issues. Using a new branch rather than a new repo might avoid a complete mess.

Absolutely, I bet people will continue filling bugs in this repository too.
